Repository vigneshshettyin/Flask-Generate-Certificate, pull requests merged in 2021-04, with the labels that each got.

#176 Auto Label
  .github/workflows/issue_label.yml
Labels: GSSOC21, Level2, enhancement

#178 [Gssoc'21] Fixed the Bug in Login feature on main page
  app.py
  static/css/style.css
  templates/index.html
Labels: GSSOC21, Level3, bug

#180 [Gssoc'21] fixed the issues in dark mode on main page
  static/css/style.css
  templates/index.html
Labels: GSSOC21, Level2, bug

#182 Made Dark Mode Better
  app.py
  static/css/sb-admin-2.css
  static/css/style.css
  static/images/forgot.png
  static/images/register.png
  static/images/why-us.jpg
  static/images/why-us.png
  templates/401.html
  templates/404.html
  templates/certificate.html
  templates/forgot-password.html
  templates/index.html
  templates/resend.html
  templates/verify.html
  templates/verify2.html
Labels: GSSOC21, Level3, enhancement

#187 Fix Certificate and Group Tables
  app.py
  templates/index.html
Labels: GSSOC21, Level3, bug

#189 Add Middleware for checking staff
  app.py
  templates/layout.html
Labels: GSSOC21, Level3, bug

#191 Transactions Table
  app.py
  templates/layout.html
  templates/transaction_table.html
Labels: GSSOC21, Level3, enhancement

#193 Replaced import.json with .env file
  .env.sample
  app.py
  config.py
  docs/INSTALLATION.md
  manage.py
  requirements.txt
  templates/certificate.html
  templates/forgot-password.html
  templates/generate.html
  templates/layout.html
  templates/login.html
  templates/register.html
  templates/resend.html
  templates/verify.html
  templates/verify2.html
Labels: GSSOC21, Level3, enhancement

#195 Separated Email Function and Templates
  app.py
  static/js/register.js
  templates/emails/account-activation.html
  templates/emails/login-alert.html
  templates/emails/new-certificate.html
  templates/emails/reset-password.html
  templates/layout.html
Labels: GSSOC21, Level3, enhancement

#201 Replaced Feedback Modal
  .gitignore
  app.py
  static/js/index.js
  templates/index.html
Labels: GSSOC21, Level3, enhancement

#203 Removed extra fields and facebook login
  app.py
  templates/login.html
  templates/register.html
Labels: GSSOC21, Level3, bug, enhancement

#205 Replace SendGrid with Gmail
  .env.sample
  app.py
  requirements.txt
Labels: GSSOC21, Level3, enhancement

#207 Fix bugs after deployment
  app.py
  manage.py
  templates/dashboard.html
  templates/layout.html
  templates/users_table.html
Labels: GSSOC21, Level3, enhancement

#208 Add Migrations
  .gitignore
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/aeab603310e4_.py
Labels: GSSOC21, Level3, enhancement

#209 Fix IP Address Length
  app.py
  migrations/env.py
  migrations/versions/5d04d3cec2b5_.py
Labels: GSSOC21, Level3, bug

#211 Fixed Google Login for deactivated users
  app.py
Labels: GSSOC21, Level3, bug

#214 [Gssoc'21] Added the Preloader
  templates/base.html
Labels: GSSOC21, Level3, enhancement

#216 Fix wkhtmltopdf and add S3 for media storage
  .env.sample
  app.py
  requirements.txt
  templates/certificate.html
Labels: GSSOC21, Level3, enhancement

#219 Fixed LinkedIn URLs for mentors
  templates/index.html
Labels: GSSOC21, Level0, documentation

#224 [Gssoc'21] Removed the dark mode from certificate.html
  templates/certificate.html
Labels: GSSOC21, Level1, bug

#225 Certificate Mockup added
  docs/certificate.md
Labels: GSSOC21, Level3, enhancement

#229 [Gssoc'21] fixed the bug in contact us in darkmode
  templates/base.html
Labels: GSSOC21, Level1, bug

#231 added certificate new template
  certificate design/assets/Leftimg.png
  certificate design/assets/bg_image.png
  certificate design/assets/cgvvignourw.png
  certificate design/assets/rightimg.png
  certificate design/assets/signature.png
  certificate design/certificate.html
  certificate design/style.css
Labels: GSSOC21, Level3, enhancement

#238 [Gssoc21] Added the dark mode in dashboard
  templates/dashboard.html
  templates/layout.html
Labels: GSSOC21, Level2, enhancement

#241 Integrated New Certificate Template
  app.py
  certificate design/assets/cgvvignourw.png
  certificate design/certificate.html
  certificate design/style.css
  static/css/certificate.css
  static/images/Leftimg.png
  static/images/bg_image.png
  static/images/rightimg.png
  static/images/signature.png
  templates/certificate.html
Labels: GSSOC21, Level3, enhancement

#244 Fix Certificate Generate Page
  app.py
Labels: GSSOC21, Level2, bug

#252 Fix User Deletion Bug
  app.py
  static/css/darkmode.css
  templates/users_table.html
Labels: GSSOC21, Level3, enhancement

#254 replaced the bootstrap modal to sweet alert for logout confirmation
  templates/index.html
  templates/layout.html
Labels: GSSOC21, Level2, enhancement

#256 Phone number validation
  static/js/index.js
  templates/base.html
Labels: GSSOC21, Level2, bug

#257 Fixed the issue with toggle
  static/css/darkmode.css
  templates/base.html
  templates/index.html
Labels: GSSOC21, Level3, bug

#258 [Gssoc'21] Added the Carousel to our contributors' section
  static/js/main.js
  templates/index.html
Labels: GSSOC21, Level3, enhancement

#259 added new generate page
  app.py
  static/images/generate.png
  templates/Redesign-generate.html
Labels: GSSOC21, Level3, enhancement

#261 social-icons modified
  static/css/style.css
  templates/index.html
Labels: GSSOC21, Level2, enhancement

#267 Add Import CSV feature in certificate
  app.py
  static/assets/sample_csv.csv
  static/js/modals.js
  templates/certificate_table.html
Labels: GSSOC21, Level3, enhancement

#268 Feedback response to csv
  app.py
  templates/contact_table.html
Labels: GSSOC21, Level3

#269 Add Export CSV Feature
  app.py
  templates/certificate_table.html
Labels: GSSOC21, Level3, enhancement

#271 Export Contact
  app.py
  templates/contact_table.html
  templates/feedback_table.html
Labels: GSSOC21, Level3, enhancement

#273 Added link to dashboard in index.html
  templates/index.html
Labels: GSSOC21, Level0

#272 Export Newsletter as csv
  app.py
  templates/newsletter_table.html
Labels: GSSOC21, Level3, enhancement

#278 added new verify page
  app.py
  templates/Redesign-verify.html
  templates/Redesign-verify2.html
Labels: GSSOC21, Level3

#280 Fix Date of Certification and Add View Certificate Button
  templates/Redesign-verify2.html
Labels: GSSOC21, Level3

#282 Fix Separate Verify Page
  app.py
  templates/Redesign-verify2.html
Labels: GSSOC21, Level3

#289 Fixed the bug in Dashboard
  static/css/darkmode.css
  templates/dashboard.html
  templates/layout.html
Labels: GSSOC21, Level3

#292 Fix Bug in View Groups
  app.py
Labels: GSSOC21, Level2, enhancement

#293 fixed the Bugs Certificate Generation page
  templates/Redesign-generate.html
  templates/base.html
  templates/index.html
Labels: GSSOC21, Level2, enhancement

#295 Fixed all the Bugs Certificate VerificationPage
  app.py
  templates/Redesign-verify2.html
  templates/base.html
  templates/index.html
Labels: GSSOC21, Level2, enhancement

#308 Fix Bug in Certificate and QR Generation
  app.py
  templates/Redesign-verify2.html
Labels: GSSOC'21, Level2
