Repository vigneshshettyin/Flask-Generate-Certificate, pull requests merged in 2021-05, with the labels that each got.

#323 added drag sidebar functionality
  static/css/style.css
  static/js/main.js
Labels: GSSOC21, Level2, enhancement

#333 Greeting Workflow Not Working
  .github/workflows/greetings.yml
Labels: GSSOC21, Level2, bug

#339 EnhanceMent in show pasword feature in login/signup
  static/js/login.js
  static/js/register.js
  templates/login.html
  templates/register.html
Labels: GSSOC21, Level1, enhancement

#352 added enhancement
  static/css/darkmode.css
  static/css/style.css
Labels: GSSOC21, Level2, bug

#366 Auto-format code on every PR
  .github/workflows/format_code.yml
Labels: GSSOC21, Level2, enhancement

#371 Fix Migrations
  app.py
  migrations/env.py
  migrations/versions/c9a0a430a7da_.py
Labels: GSSOC21, Level3

#372 Fix Migrations
  migrations/versions/36ecc35f52f7_.py
  migrations/versions/c9a0a430a7da_.py
  migrations/versions/eabd7ab06af3_.py
Labels: GSSOC21, Level2, bug

#376 fixed the toggle button
  templates/Redesign-generate.html
  templates/Redesign-verify2.html
  templates/index.html
Labels: GSSOC21, Level1, bug

#381 Readme
  README.md
Labels: GSSOC21, Level0, documentation

#382 popup profile template added
  templates/pop-up-profilepage/index.html
  templates/pop-up-profilepage/unnamed.png
Labels: GSSOC21, Level3, enhancement

#383 done the whole react setup
  .env
  .github/public/favicon.ico
  .github/public/index.html
  .github/public/logo192.png
  .github/public/logo512.png
  .github/public/manifest.json
  .github/public/robots.txt
  .gitignore
  README.md
  docs/src/App.css
  docs/src/App.js
  docs/src/App.test.js
  docs/src/index.css
  docs/src/index.js
  docs/src/logo.svg
  docs/src/reportWebVitals.js
  docs/src/setupTests.js
  package-lock.json
  package.json
Labels: GSSOC21, Level3, enhancement

#387 Dynamic Certificate Generation and Bug Fixes
  .gitignore
  app.py
  migrations/env.py
  migrations/versions/31e3e4a7ed93_.py
  migrations/versions/36ecc35f52f7_.py
  migrations/versions/5d04d3cec2b5_.py
  migrations/versions/80b7c849b13f_.py
  requirements.txt
  static/css/certificate.css
  static/js/modals.js
  templates/certificate.html
Labels: GSSOC21, Level3, enhancement

#386 made frontend folder for react
  frontend/.gitignore
  frontend/README-React.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: GSSOC21, Level3, enhancement

#389 done eslint setup
  frontend/.eslintrc.js
  frontend/package.json
Labels: GSSOC21, Level1, enhancement

#391 API Key model and tables in dashboard
  app.py
  migrations/versions/0cdc67d32d06_.py
  migrations/versions/24161eac56c6_.py
  static/js/modals.js
  templates/api_admin_table.html
  templates/api_users_table.html
  templates/layout.html
Labels: GSSOC21, Level3, enhancement

#392 Create Certificate API
  app.py
  requirements.txt
Labels: GSSOC21, Level3, enhancement

#406 Added API Documentation
  app.py
  requirements.txt
  static/assets/cgv_api_doc.json
  static/css/swagger-ui.css
  static/js/swagger-ui-bundle.js
  static/js/swagger-ui-standalone-preset.js
  templates/api_users_table.html
  templates/layout.html
Labels: GSSOC21, Level3, enhancement

#417 Integrated Profile Page
  .gitignore
  app.py
  templates/layout.html
  templates/pop-up-profilepage/index.html
Labels: GSSOC21, Level3, enhancement

#420 added dark mode UI
  frontend/src/App.js
  frontend/src/index.js
Labels: GSSOC21, Level3, enhancement

#426 Converted the certificate design1 into code
  templates/certificatedesign1/cert.html
  templates/certificatedesign1/certificate.png
  templates/certificatedesign1/qr_code.png
  templates/certificatedesign1/script.js
Labels: GSSOC21, Level3, enhancement

#428 deployment on Google Cloud
  docs/Google_Cloud.md
Labels: GSSOC21, Level2, enhancement

#431 deployment in Digital Ocean Platform
  docs/Digital_Ocean.md
Labels: GSSOC21, Level2, documentation

#430 deployment in Azure App Services
  docs/Azure.md
Labels: GSSOC21, Level2, documentation

#432 Modification in certificate design2
  templates/certificate design2/cert2.html
  templates/certificate design2/certificate.png
  templates/certificate design2/qr_code.png
  templates/certificate design2/script.js
Labels: GSSOC21, Level3, enhancement

#435 fixed a bug
  static/css/style.css
Labels: GSSOC21, Level2, bug

#436 Add Public API
  app.py
  docs/INSTALLATION.md
  migrations/versions/0855df808efb_.py
  migrations/versions/fd310d78e3f7_.py
  requirements.txt
  static/js/modals.js
  templates/layout.html
  templates/private_api_admin_table.html
  templates/private_api_users_table.html
  templates/public_api_admin_table.html
  templates/public_api_users_table.html
Labels: GSSOC21, Level3

#441 added content about routes of the available endpoints
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/Contact.js
  frontend/src/Home.js
  frontend/src/Main.js
  frontend/src/Routes.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/components/Motive/Motive.jsx
  frontend/src/pages/Home/components/Motive/index.js
  frontend/src/pages/Home/components/Motive/motive.module.scss
  frontend/src/pages/Home/components/Overview/Overview.jsx
  frontend/src/pages/Home/components/Overview/index.js
  frontend/src/pages/Home/components/Overview/overview.module.scss
  frontend/src/pages/Home/home.module.scss
  frontend/src/pages/Home/index.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: GSSOC21, Level3, enhancement

#448 banner added
  README.md
Labels: GSSOC21, Level2, documentation

#455 added GSSoC certificate template
  templates/GSSoC'Certificate/cert.html
  templates/GSSoC'Certificate/certificatecdnlink.txt
  templates/GSSoC'Certificate/qrcodecdnlink.txt
Labels: GSSOC21, Level3, enhancement

#456 Added certificatedesign1 modified design
  templates/certificatedesign1/cert.html
  templates/certificatedesign1/cert1.html
  templates/certificatedesign1/certificate.png
  templates/certificatedesign1/certificatecdnlink.txt
  templates/certificatedesign1/qr_code.png
  templates/certificatedesign1/qrcodecdnlink.txt
  templates/certificatedesign1/script.js
Labels: GSSOC21, Level3, enhancement

#457 Added certificate2 modified design
  templates/certificate design2/cert2.html
  templates/certificate design2/certificate.png
  templates/certificate design2/certificatecdnlink.txt
  templates/certificate design2/qr_code.png
  templates/certificate design2/qrcodecdnlink.txt
  templates/certificate design2/script.js
Labels: GSSOC21, Level2, enhancement

#460 Typo Fix & Documentation Improvement
  README.md
Labels: GSSOC21, Level2, documentation

#461 Bug removed
  docs/certificate.md
  templates/GSSoC'Certificate/cert.html
Labels: GSSOC21, Level3, bug

#462 Bug Removed in certificate design1
  docs/certificate.md
  templates/certificate design2/cert2.html
  templates/certificatedesign1/cert1.html
Labels: GSSOC21, Level3, enhancement
