Repository vigneshshettyin/Flask-Generate-Certificate, pull requests merged in 2021-06, with the labels that each got.

#467 Category Section
  .idea/.gitignore
  .idea/Flask-Generate-Certificate.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  app.py
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/0855df808efb_.py
  migrations/versions/0cdc67d32d06_.py
  migrations/versions/24161eac56c6_.py
  migrations/versions/31e3e4a7ed93_.py
  migrations/versions/80b7c849b13f_.py
  migrations/versions/fd310d78e3f7_.py
  package-lock.json
  package.json
  requirements.txt
  static/assets/cgv_api_doc.json
  static/js/modals.js
  templates/GSSoC'Certificate/cert.html
  templates/GSSoC'Certificate/certificatecdnlink.txt
  templates/GSSoC'Certificate/qrcodecdnlink.txt
  templates/certificate design2/cert2.html
  templates/certificate design2/certificatecdnlink.txt
  templates/certificate design2/qrcodecdnlink.txt
  templates/certificate.html
  templates/certificatedesign1/cert1.html
  templates/certificatedesign1/certificatecdnlink.txt
  templates/certificatedesign1/qrcodecdnlink.txt
  templates/layout.html
  templates/org_table.html
  templates/pop-up-profilepage/index.html
  templates/pop-up-profilepage/unnamed.png
  templates/private_api_users_table.html
Labels: enhancement, help wanted, python

#474 Fix issues
  .env.sample
  app.py
  docs/INSTALLATION.md
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/5c027f8caf84_.py
  static/js/modals.js
  templates/certificate.html
Labels: bug, python

#475 Add Postman API Docs
  static/assets/cgv_api_doc.json
  static/js/swagger-ui-bundle.js
  static/js/swagger-ui-standalone-preset.js
  templates/private_api_users_table.html
  templates/public_api_users_table.html
Labels: Top Contributor, python

#479 Add APIs
  .env.sample
  app.py
  migrations/versions/453d6c4c6fef_.py
  requirements.txt
  templates/font_table.html
  templates/layout.html
  templates/private_api_users_table.html
Labels: Top Contributor, python

#482 small fix
  static/css/style.css
Labels: bug

#507 small fix
  templates/index.html
Labels: bug
