Repository vigneshshettyin/Flask-Generate-Certificate, pull requests merged in 2021-03, with the labels that each got.

#3 Added Hover effect
  static/css/style.css
Labels: GSSOC'21, Intermediate, good first issue

#8 Added auto labeling script
  .github/workflows/label.yml
Labels: GSSOC'21

#13 Added issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/assign.yaml
Labels: GSSOC'21

#18 Fix Email and Password Regex Validation
  app.py
  static/js/register.js
  templates/register.html
Labels: GSSOC21, Level3

#21 Solved bugs
  .github/workflows/label.yml
  README.md
Labels: GSSOC21, LEVEL2

#26 Fix Razorpay Integration
  .gitignore
  app.py
  import.json
  requirements.txt
  static/css/style.css
  static/js/index.js
  templates/base.html
  templates/index.html
  templates/razorpay.html
Labels: GSSOC21, Level3

#29 Added a pull request template
  .github/pull_request_template.md
Labels: GSSOC21, Level0

#28 Update all contributors
  app.py
  templates/index.html
Labels: GSSOC21, Level3

#30 Add different badges to the README
  README.md
Labels: GSSOC21, LEVEL2, documentation

#36 Add Logo in README
  README.md
Labels: GSSOC21, Level0

#40 Changed the border color of Send message and Razor pay button
  .idea/vcs.xml
  templates/base.html
  templates/index.html
Labels: GSSOC21, Level0

#41 Added space between get started and contact us button in mobile version
  templates/index.html
Labels: GSSOC21, Level0

#48 Fix Contributors Data
  app.py
Labels: GSSOC21, Level3

#50 Add QR Code Generation for certificates
  app.py
  cgv.db
  requirements.txt
  templates/certificate.html
Labels: GSSOC21, Level3

#59 Update index.html
  templates/index.html
Labels: GSSOC21, Level1

#61 Updated "How to Use" section in README
  README.md
Labels: GSSOC21, Level0

#65 Fix Contributors Data
  app.py
  import.json
Labels: GSSOC21, LEVEL2, bug

#69 changed the order of Pricing and Team section as per the nav bar
  templates/index.html
Labels: GSSOC21, LEVEL2

#70 "fixes the bug in form validation"
  app.py
  templates/base.html
  templates/index.html
Labels: GSSOC21, Level3

#73 Improved Templates
  .github/ISSUE_TEMPLATE/Improve existing docs.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: GSSOC21, Level0

#75 fix the redirect link
  templates/index.html
Labels: GSSOC21, Level0, bug

#80 Fixes Issue #57 : Dockerized the project
  Dockerfile
  README.md
  app.py
  docker-compose.yml
Labels: GSSOC21, Level3

#82 Change API to local api
  app.py
  import.json
Labels: GSSOC21, Level3, enhancement

#89 Add Google Login, Add Gravatar Support and Profile Image in Users Table
  .gitignore
  app.py
  import.json
  requirements.txt
  templates/401.html
  templates/layout.html
  templates/login.html
Labels: GSSOC21, Level3, enhancement

#90 Fix Payment Form Submission when empty fields
  static/js/index.js
  templates/base.html
  templates/razorpay.html
Labels: GSSOC21, Level2, bug

#93 Remove models to avoid circular import
  app.py
  migrations/versions/727d85c4169e_.py
  models.py
Labels: GSSOC21, Level2, bug

#96 Fixed the bug in Navbar
  templates/index.html
Labels: GSSOC21, Level0, bug

#85 Corrected a grammatical error
  README.md
Labels: GSSOC21, Level0

#101 Refactored docs
  docs/AWS.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/DOCKER.md
  docs/INSTALLATION.md
  docs/INSTRUCTIONS.md
Labels: GSSOC21, Level0, documentation

#102 Change Organization to Group, Add Modals for Certificate, Group
  app.py
  migrations/env.py
  migrations/versions/1d0d4b07df15_.py
  static/js/modals.js
  templates/add_edit_certificate.html
  templates/add_edit_org.html
  templates/certificate_table.html
  templates/layout.html
  templates/org_table.html
Labels: GSSOC21, Level3, enhancement

#103 Updating the links in README
  Documentation/CODE_OF_CONDUCT.md
  Documentation/CONTRIBUTING.md
  Documentation/INSTRUCTIONS.md
  Documentation/aws.md
  README.md
Labels: GSSOC21, Level0, documentation

#138 Gssoc'21 New And Cool Toggle Button Added
  static/css/style.css
  static/js/darkmode.js
  templates/base.html
  templates/index.html
  templates/login.html
  templates/register.html
Labels: GSSOC21, Level3, enhancement

#139 Reset Password using verification link
  app.py
  static/js/reset-pwd.js
  templates/dashboard.html
  templates/forgot-password.html
Labels: GSSOC21, Level3, enhancement

#148 color changes
  static/css/sb-admin-2.css
  static/images/login.png
  templates/forgot-password.html
  templates/login.html
  templates/register.html
  templates/resend.html
Labels: GSSOC21, Level2, enhancement

#147 right click enabled
  templates/base.html
  templates/index.html
Labels: GSSOC21, Level2, enhancement

#157 [Gssoc'21] Fix the Bug in Register page.
  static/js/register.js
  templates/base.html
  templates/index.html
  templates/register.html
Labels: GSSOC21, Level3, bug

#161 Certificate PDF Conversion without API
  app.py
  requirements.txt
  templates/certificate.html
Labels: GSSOC21, Level3, enhancement

#166 Token Bug Fix and Flash replaced with Simple-Notify
  app.py
  import.json
  migrations/versions/77094592831e_.py
  migrations/versions/fca98213172f_.py
  static/css/simple-notify.min.css
  static/js/simple-notify.min.js
  templates/add_edit_users.html
  templates/base.html
  templates/certificate_table.html
  templates/contact_table.html
  templates/feedback_table.html
  templates/forgot-password.html
  templates/generate.html
  templates/layout.html
  templates/login.html
  templates/mail.html
  templates/newsletter_table.html
  templates/org_table.html
  templates/register.html
  templates/resend.html
  templates/users_table.html
  templates/verify.html
  templates/verify2.html
Labels: GSSOC21, Level3, enhancement

#169 [Gssoc'21] Fix the decrease the size of toggle button
  static/css/darkmode.css
  static/css/style.css
  templates/base.html
  templates/login.html
  templates/register.html
Labels: GSSOC21, Level3, enhancement

#172 fix the Issues in style.css
  static/css/style.css
  templates/index.html
Labels: GSSOC21, Level2, bug
